const sampleCars = [
  // TOYOTA
  {
    id: 1,
    name: "Renault Duster RXZ+",
    model: "1.8L Hybrid",
    year: 2016,
    price: 2250000,
    fuelType: "Disel",
    kmsRan: 62000,
    condition: "Excellent",
    image: "Upload/Duster.jpeg",
    rating: 4.5,
    location: "Lalitpur, Nepal",
    transmission: "Automatic",
    engine: "1.5 dCI K9K THP Diesel engine",
    bodyType: "SUV",
    color: "Orange",
    seats: 5,
    doors: 4,
    features: [
      "Fully Loaded",
      "Turbocharged Engine",
      "All-Wheel Drive",
      "Panoramic Sunroof",
      "Leather Seats",
      "Navigation System",
      "Bluetooth Connectivity",
    ],
    images: [
      "Upload/Duster.jpeg",
      "Upload/Duster2.jpeg",
      "Upload/Duster3.jpeg",
      "Upload/Duster4.jpeg",
      "Upload/Duster5.jpeg",
    ],
  },
  {
    id: 2,
    name: "Datsun Go",
    model: "1.5L Hybrid",
    year: 2017,
    price: 1250000,
    fuelType: "Hybrid",
    kmsRan: 39100,
    condition: "Excellent",
    image: "Upload/datsun.jpeg",
    rating: 4.5,
    location: "Kathmandu, Nepal",
    transmission: "CVT Automatic",
    engine: "1.5L Hybrid Synergy Drive",
    bodyType: "Hatchback",
    color: "Sky Blue",
    seats: 5,
    doors: 4,
    features: [
      "Fully Loaded",
      "Turbocharged Engine",
      "All-Wheel Drive",
      "Panoramic Sunroof",
      "Leather Seats",
      "Navigation System",
      "Bluetooth Connectivity",
    ],
    images: [
      "Upload/datsun.jpeg",
      "Upload/datsun1.jpeg",
      "Upload/datsun2.jpeg",
      "Upload/datsun3.jpeg",
      "Upload/datsun4.jpeg",
    ],
  },

  // SUZUKI
  {
    id: 3,
    name: "Hyundai Santro",
    model: "1.2L VVT Petrol",
    year: 2010,
    price: 1150000,
    fuelType: "Petrol",
    kmsRan: 24800,
    condition: "Excellent",
    image: "Upload/santro.jpeg",
    rating: 4.5,
    location: "Pokhara, Nepal",
    transmission: "5-speed Manual",
    engine: "1.2L 4-cylinder VVT",
    bodyType: "Hatchback",
    color: "Red",
    seats: 5,
    doors: 4,
    features: [
      "Fully Loaded",
      "Turbocharged Engine",
      "All-Wheel Drive",
      "Panoramic Sunroof",
      "Leather Seats",
      "Navigation System",
      "Bluetooth Connectivity",
    ],
    images: [
      "Upload/santro.jpeg",
      "Upload/santro1.jpeg",
      "Upload/santro2.jpeg",
      "Upload/santro3.jpeg",
      "Upload/santro4.jpeg",
    ],
  },
  {
    id: 4,
    name: "Suzuki Baleno",
    model: "1.2L DualJet",
    year: 2018,
    price: 5995000,
    fuelType: "Petrol",
    kmsRan: 36200,
    condition: "Excellent",
    image: "Upload/baleno.jpg",
    rating: 4.5,
    location: "Bhaktapur, Nepal",
    transmission: "CVT Automatic",
    engine: "1.2L K12 DualJet",
    bodyType: "Hatchback",
    color: "Gray",
    seats: 5,
    doors: 4,
    features: [
      "Fully Loaded",
      "Turbocharged Engine",
      "All-Wheel Drive",
      "Panoramic Sunroof",
      "Leather Seats",
      "Navigation System",
      "Bluetooth Connectivity",
    ],
    images: ["Upload/baleno.jpg", "Upload/baleno1.avif", "Upload/baleno2.jpg"],
  },

  // HYUNDAI
  {
    id: 5,
    name: "Hyundai Creta",
    model: "1.6L Petrol SX",
    year: 2019,
    price: 5995000,
    fuelType: "Petrol",
    kmsRan: 51000,
    condition: "Excellent",
    image: "Upload/Creta.jpeg",
    rating: 4.5,
    location: "Kathmandu, Nepal",
    transmission: "6-speed Manual",
    engine: "1.6L Gamma Petrol",
    bodyType: "SUV",
    color: "Phantom Black",
    seats: 5,
    doors: 4,
    features: [
      "Fully Loaded",
      "Turbocharged Engine",
      "All-Wheel Drive",
      "Panoramic Sunroof",
      "Leather Seats",
      "Navigation System",
      "Bluetooth Connectivity",
    ],
    images: ["Upload/Creta.jpeg", "Upload/creta1.jpeg"],
  },

  {
    id: 6,
    name: "Hyundai i20",
    model: "1.2L Kappa Petrol",
    year: 2020,
    price: 5995000,
    fuelType: "Petrol",
    kmsRan: 20700,
    condition: "Excellent",
    image: "Upload/i20.webp",
    rating: 4.5,
    location: "Butwal, Nepal",
    transmission: "IVT Automatic",
    engine: "1.2L Kappa Dual VTVT",
    bodyType: "Hatchback",
    color: "Titan Gray",
    seats: 5,
    doors: 4,
    features: [
      "Fully Loaded",
      "Turbocharged Engine",
      "All-Wheel Drive",
      "Panoramic Sunroof",
      "Leather Seats",
      "Navigation System",
      "Bluetooth Connectivity",
    ],
    images: ["Upload/i20.webp", "Upload/i201.jpeg", "Upload/i202.jpeg"],
  },

  // HONDA
  {
    id: 7,
    name: "Honda Fit",
    model: "1.3L Hybrid",
    year: 2015,
    price: 5995000,
    fuelType: "Hybrid",
    kmsRan: 34200,
    condition: "Excellent",
    image: "Upload/fit.jpeg",
    rating: 4.5,
    location: "Kathmandu, Nepal",
    transmission: "CVT Automatic",
    engine: "1.3L i-VTEC Hybrid",
    bodyType: "Hatchback",
    color: "Metallic Blue",
    seats: 5,
    doors: 4,
    features: [
      "Fully Loaded",
      "Turbocharged Engine",
      "All-Wheel Drive",
      "Panoramic Sunroof",
      "Leather Seats",
      "Navigation System",
      "Bluetooth Connectivity",
    ],
    images: ["Upload/fit.jpeg", "Upload/git1.avif", "Upload/fit2.jpg"],
  },

  {
    id: 8,
    name: "Honda Vezel",
    model: "1.5L i-VTEC Hybrid",
    year: 2016,
    price: 5995000,
    fuelType: "Hybrid",
    kmsRan: 48300,
    condition: "Excellent",
    image: "Upload/vezel.jpg",
    rating: 4.5,
    location: "Patan, Nepal",
    transmission: "7-Speed DCT",
    engine: "1.5L i-VTEC Hybrid",
    bodyType: "SUV",
    color: "Champagne Gold",
    seats: 5,
    doors: 4,
    features: [
      "Fully Loaded",
      "Turbocharged Engine",
      "All-Wheel Drive",
      "Panoramic Sunroof",
      "Leather Seats",
      "Navigation System",
      "Bluetooth Connectivity",
    ],
    images: ["Upload/vezel.jpg", "upload/vezel1.jpeg", "Upload/vezel2.jpeg"],
  },

  // NISSAN
  {
    id: 9,
    name: "Nissan Leaf",
    model: "EV ZE1",
    year: 2020,
    price: 5995000,
    fuelType: "Electric",
    kmsRan: 15200,
    condition: "Excellent",
    image: "Upload/leaf.JPG",
    rating: 4.5,
    location: "Kathmandu, Nepal",
    transmission: "Single Speed",
    engine: "40kWh Electric Motor",
    bodyType: "Hatchback",
    color: "Pearl White",
    seats: 5,
    doors: 4,
    features: [
      "Fully Loaded",
      "Turbocharged Engine",
      "All-Wheel Drive",
      "Panoramic Sunroof",
      "Leather Seats",
      "Navigation System",
      "Bluetooth Connectivity",
    ],
    images: ["Upload/leaf1.jpg", "Upload/leaf.JPG", "Upload/leaf2.webp"],
  },

  // MITSUBISHI
  {
    id: 10,
    name: "Mitsubishi Outlander",
    model: "2.4L Petrol AWD",
    year: 2017,
    price: 5995000,
    fuelType: "Petrol",
    kmsRan: 58600,
    condition: "Excellent",
    image: "Upload/out.jpg",
    rating: 4.5,
    location: "Itahari, Nepal",
    transmission: "CVT with 6-step Sports Mode",
    engine: "2.4L MIVEC DOHC",
    bodyType: "SUV",
    color: "Dark Red",
    seats: 5,
    doors: 4,
    features: [
      "Fully Loaded",
      "Turbocharged Engine",
      "All-Wheel Drive",
      "Panoramic Sunroof",
      "Leather Seats",
      "Navigation System",
      "Bluetooth Connectivity",
    ],
    images: ["Upload/out.jpg", "Upload/out1.jpg", "Upload/out2.avif"],
  },

  // MAHINDRA
  {
    id: 11,
    name: "Mahindra Scorpio",
    model: "2.2L mHawk S10",
    year: 2018,
    price: 5995000,
    fuelType: "Diesel",
    kmsRan: 63500,
    condition: "Excellent",
    image: "Upload/sco.jpeg",
    rating: 4.5,
    location: "Kathmandu, Nepal",
    transmission: "6-speed Manual",
    engine: "2.2L mHawk Diesel",
    bodyType: "SUV",
    color: "Black",
    seats: 7,
    doors: 5,
    features: [
      "Fully Loaded",
      "Turbocharged Engine",
      "All-Wheel Drive",
      "Panoramic Sunroof",
      "Leather Seats",
      "Navigation System",
      "Bluetooth Connectivity",
    ],
    images: ["Upload/sco.jpeg", "Upload/sco1.jpeg", "Upload/sco2.avif"],
  },
];

export default sampleCars;
